### ISSUE TITLE
Script is broken again

### ISSUE THREAD

**Issue by Dyras** [Rsge/GreaterGood-CTG-AutoClicker#2]
Hello!

A new update has seemingly struck the website again. You're supposed to be directed from the "thank you" page to the next free click, and currently you're not.

Thanks for the script so far!

**Comment by Rsge** [comment]
That's ... odd.
I just tested it again, for me it's still running perfectly fine, even with the "new" website boasting the additional "Click for Paws" button. It's just stopping at Literacy instead of GG or Rainforest as before.

Could you double-check that you have the newest version and look at the console for errors? Maybe also send a screenshot of how the site is looking on your side. Which browser are you using? Not that it *should* make a difference...

**Comment by Dyras** [comment]
Hello! I'm using Microsoft Edge if that matters. Tracking protection and Enhanced Security are both disabled. I tried checking for updates to the script, but I'm already on the latest version.
<img width="1345" alt="image" src="https://github.com/Rsge/GreaterGood-CTG-AutoClicker/assets/12563436/965a3181-05ff-4414-9413-4c72bb1ec8c1">


This is the error message I'm getting:

```
GreaterGood CTG Auto-Klicker.user.js:70  Uncaught TypeError: window.open is not a function
    at GreaterGood CTG Auto-Klicker.user.js:70:14
    at GreaterGood CTG Auto-Klicker.user.js:78:3
    at VMcbppqmbvof8 (GreaterGood CTG Auto-Klicker.user.js:79:3)
    at Ut (injected-web.js:1:14233)
    at GreaterGood CTG Auto-Klicker.user.js:1:20
    at async $t (injected.js:1:8168)
    at async injected.js:1:13208
```

**Comment by Dyras** [comment]
It's working now for some reason. Will reopen if it happens again!

**Comment by Rsge** [comment]
I tried reproducing your issue with a "clean" Edge (only TM and the script installed), too, and couldn't reproduce the error.
It even works while the cookie acceptance window is still open (which on my main FF closes because of Consent Manager or ISDCAC).
If you get it again I'd be interested in more details about your installation.

One possibility I see is Tampermonkey or some other part of Edge having a bug that Firefox hasn't and that got fixed in the meantime.

Thank you for reporting this anyway, I'll also keep an eye on it, maybe someone else will have this problem sometime, too.
